apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aatiwarishub2aks-c4fd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aatiwarishub2aks-c4fd"
  template:
    metadata:
      labels:
        app: "aatiwarishub2aks-c4fd"
    spec:
      containers:
        - name: "aatiwarishub2aks-c4fd"
          image: "aaaatiwarishubregistry.azurecr.io/aatiwarishub2aksc4fd"
          ports:
          - containerPort: 4000