apiVersion: v1
kind: Service
metadata:
    name: "aatiwarishubaks-cfce"
    labels:
        app: "aatiwarishubaks-cfce"
spec:
    type: ClusterIP
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aatiwarishubaks-cfce"
