apiVersion: v1
kind: Service
metadata:
    name: "aaaatiwarishubaks-f701"
    labels:
        app: "aaaatiwarishubaks-f701"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "aaaatiwarishubaks-f701"