on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.aatiwarishub1aksacr_43b8}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aatiwarishub1aksacr -g aatiwarishub1aksacr81e7-rg --location "South Central US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aatiwarishub1aksacr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aatiwarishub1aksacr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aatiwarishub1aksacr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: aatiwarishub1aksacr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t aatiwarishub1aksacr.azurecr.io/aatiwarishubaks43b8:${{ github.sha }}
        docker push aatiwarishub1aksacr.azurecr.io/aatiwarishubaks43b8:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_aatiwarishubaks_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aatiwarishubaks43b8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aatiwarishubaks43b8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aatiwarishubaks43b8
        container-registry-url: aatiwarishub1aksacr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aatiwarishubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aatiwarishubaks43b8
        manifests: |
          ./manifests/deployment-43b8.yml
          ./manifests/service-43b8.yml
        images: |
          aatiwarishub1aksacr.azurecr.io/aatiwarishubaks43b8:${{ github.sha }}
        imagepullsecrets: |
          aatiwarishubdockerauth